### ISSUE TITLE
Server crashes with every SendPhoneRequest

### ISSUE THREAD

**Issue by bredmich** [mhdawson/micro-app-phone-dialer#2]
Hi Michael,

i came accross your great idea for this small Cisco Phone Dialer and would like to use it.
Currently i´m not able to get it running.

My setup:
- Windows Server 2016 Standard (ESXi VM)
- Node 13.5.0 / npm 6.13.4

Nodejs is installed in the standard folder `C:\Program Files\nodejs\`
I started with installing the `micro-app-framework`, `node-cti` and `micro-app-phone-dialer`
The install worked fine without errors and the following modules are installed:
```.bin
basic-auth
bcryptjs
crypto-js
micro-app-electron-launcher
micro-app-framework
micro-app-phone-dialer
node-cti
npm
```

I filled the values in `\nodejs\node_modules\micro-app-phone-dialer\lib\config.json`
`"serverPort": 8083,`
`"phoneIP": "192.168.2.X",`
And added one direct line based on your examples.

So when i´m starting the server from the command prompt inside the `\nodejs\node_modules\micro-app-phone-dialer` directory, the server starts and i´m able to open the Phone Dialer on the locale machine or any other browser in my network.
But whatever i´ll choose, the server crashes and i´m not able to figure out why.

Here´s what the command prompt prints:
```
C:\Program Files\nodejs\node_modules\micro-app-phone-dialer>npm start

> micro-app-phone-dialer@1.0.6 start C:\Program Files\nodejs\node_modules\micro-app-phone-dialer
> node lib/server.js

C:\Program Files\nodejs\node_modules\micro-app-phone-dialer\lib\server.js:92
            throw(resonse.statusCode);
            ^

ReferenceError: resonse is not defined
    at C:\Program Files\nodejs\node_modules\micro-app-phone-dialer\lib\server.js:92:13
    at ClientRequest.<anonymous> (C:\Program Files\nodejs\node_modules\node-cti\lib\SendPhoneRequest.js:55:61)
    at Object.onceWrapper (events.js:412:26)
    at ClientRequest.emit (events.js:305:20)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:601:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:116:17)
    at Socket.socketOnData (_http_client.js:470:22)
    at Socket.emit (events.js:305:20)
    at addChunk (_stream_readable.js:341:12)
    at readableAddChunk (_stream_readable.js:316:11)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! micro-app-phone-dialer@1.0.6 start: `node lib/server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the micro-app-phone-dialer@1.0.6 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2020-01-03T16_04_25_546Z-debug.log
```

And the linked logfile:
```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start'
1 verbose cli ]
2 info using npm@6.13.4
3 info using node@v13.5.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle micro-app-phone-dialer@1.0.6~prestart: micro-app-phone-dialer@1.0.6
6 info lifecycle micro-app-phone-dialer@1.0.6~start: micro-app-phone-dialer@1.0.6
7 verbose lifecycle micro-app-phone-dialer@1.0.6~start: unsafe-perm in lifecycle true
8 verbose lifecycle micro-app-phone-dialer@1.0.6~start: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Program Files\nodejs\node_modules\micro-app-phone-dialer\node_modules\.bin;C:\Program Files\nodejs\node_modules\.bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;D:\Program Files (x86)\Microsoft SQL Server\150\DTS\Binn\;c:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\;c:\Program Files (x86)\Microsoft SQL Server\100\DTS\Binn\;D:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\;D:\Program Files\Microsoft SQL Server\140\Tools\Binn\;D:\Program Files (x86)\Microsoft SQL Server\140\DTS\Binn\;D:\Program Files\Microsoft SQL Server\140\DTS\Binn\;D:\Program Files\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files\nodejs\;C:\Users\Administrator\AppData\Local\Microsoft\WindowsApps;C:\Users\Administrator\AppData\Roaming\npm
9 verbose lifecycle micro-app-phone-dialer@1.0.6~start: CWD: C:\Program Files\nodejs\node_modules\micro-app-phone-dialer
10 silly lifecycle micro-app-phone-dialer@1.0.6~start: Args: [ '/d /s /c', 'node lib/server.js' ]
11 silly lifecycle micro-app-phone-dialer@1.0.6~start: Returned: code: 1  signal: null
12 info lifecycle micro-app-phone-dialer@1.0.6~start: Failed to exec start script
13 verbose stack Error: micro-app-phone-dialer@1.0.6 start: `node lib/server.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:305:20)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:305:20)
13 verbose stack     at maybeClose (internal/child_process.js:1028:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid micro-app-phone-dialer@1.0.6
15 verbose cwd C:\Program Files\nodejs\node_modules\micro-app-phone-dialer
16 verbose Windows_NT 10.0.14393
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v13.5.0
19 verbose npm  v6.13.4
20 error code ELIFECYCLE
21 error errno 1
22 error micro-app-phone-dialer@1.0.6 start: `node lib/server.js`
22 error Exit status 1
23 error Failed at the micro-app-phone-dialer@1.0.6 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

Do you have any idea what i may missed?

Thanks and kind regards
Michael

**Comment by derandre24** [comment]
Hi Michael,

i believe i have the same issue.

here my npm-debug.log:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@1.4.21
3 info using node@v8.11.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart micro-app-phone-dialer@1.0.6
6 info start micro-app-phone-dialer@1.0.6
7 verbose unsafe-perm in lifecycle true
8 info micro-app-phone-dialer@1.0.6 Failed to exec start script
9 error micro-app-phone-dialer@1.0.6 start: `node lib/server.js`
9 error Exit status 1
10 error Failed at the micro-app-phone-dialer@1.0.6 start script.
10 error This is most likely a problem with the micro-app-phone-dialer package,
10 error not with npm itself.
10 error Tell the author that this fails on your system:
10 error     node lib/server.js
10 error You can get their info via:
10 error     npm owner ls micro-app-phone-dialer
10 error There is likely additional logging output above.
11 error System Linux 4.14.79+
12 error command "/usr/bin/node" "/usr/bin/npm" "start"
13 error cwd /usr/local/lib/node_modules/micro-app-phone-dialer
14 error node -v v8.11.1
15 error npm -v 1.4.21
16 error code ELIFECYCLE
17 verbose exit [ 1, true ]

And the output on the server

npm start
(node:18343) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.

> micro-app-phone-dialer@1.0.6 start /usr/local/lib/node_modules/micro-app-phone-dialer
> node lib/server.js

/usr/local/lib/node_modules/micro-app-phone-dialer/lib/server.js:92
            throw(resonse.statusCode);
            ^

ReferenceError: resonse is not defined
    at /usr/local/lib/node_modules/micro-app-phone-dialer/lib/server.js:92:13
    at ClientRequest.http.request.response (/usr/local/lib/node_modules/micro-app-phone-dialer/node_modules/node-cti/lib/SendPhoneRequest.js:55:61)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:551:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:115:23)
    at Socket.socketOnData (_http_client.js:440:20)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)

npm ERR! micro-app-phone-dialer@1.0.6 start: `node lib/server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the micro-app-phone-dialer@1.0.6 start script.
npm ERR! This is most likely a problem with the micro-app-phone-dialer package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node lib/server.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls micro-app-phone-dialer
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 4.14.79+
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! cwd /usr/local/lib/node_modules/micro-app-phone-dialer
npm ERR! node -v v8.11.1
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /usr/local/lib/node_modules/micro-app-phone-dialer/npm-debug.log
npm ERR! not ok code 0


Thanks and kind regards
Andre

**Comment by mhdawson** [comment]
I can see there is a typo in throw(resonse.statusCode);  

It should be response.statusCode (original is missing p).

If you edit that and then re-run it should at least give you the status code that is being returned by the phone.

Let me know after you do that.

**Comment by bredmich** [comment]
Hi Michael,

i already saw that and tried it but didn´t followed as it still made some errors.
It just throws and 401 error.

It doesn´t matter what i try to send: MUTE, Dial:0 or HANGUP

```
C:\Program Files\nodejs\node_modules\micro-app-phone-dialer>npm start

> micro-app-phone-dialer@1.0.6 start C:\Program Files\nodejs\node_modules\micro-app-phone-dialer
> node lib/server.js


C:\Program Files\nodejs\node_modules\micro-app-phone-dialer\lib\server.js:92
            throw(response.statusCode);
            ^
401
(Use `node --trace-uncaught ...` to show where the exception was thrown)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! micro-app-phone-dialer@1.0.6 start: `node lib/server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the micro-app-phone-dialer@1.0.6 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2020-01-06T19_46_12_131Z-debug.log
```

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start'
1 verbose cli ]
2 info using npm@6.13.4
3 info using node@v13.5.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle micro-app-phone-dialer@1.0.6~prestart: micro-app-phone-dialer@1.0.6
6 info lifecycle micro-app-phone-dialer@1.0.6~start: micro-app-phone-dialer@1.0.6
7 verbose lifecycle micro-app-phone-dialer@1.0.6~start: unsafe-perm in lifecycle true
8 verbose lifecycle micro-app-phone-dialer@1.0.6~start: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Program Files\nodejs\node_modules\micro-app-phone-dialer\node_modules\.bin;C:\Program Files\nodejs\node_modules\.bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;D:\Program Files (x86)\Microsoft SQL Server\150\DTS\Binn\;c:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\;c:\Program Files (x86)\Microsoft SQL Server\100\DTS\Binn\;D:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\;D:\Program Files\Microsoft SQL Server\140\Tools\Binn\;D:\Program Files (x86)\Microsoft SQL Server\140\DTS\Binn\;D:\Program Files\Microsoft SQL Server\140\DTS\Binn\;D:\Program Files\Microsoft SQL Server\Client SDK\ODBC\130\Tools\Binn\;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files\nodejs\;C:\Users\Administrator\AppData\Local\Microsoft\WindowsApps;C:\Users\Administrator\AppData\Roaming\npm
9 verbose lifecycle micro-app-phone-dialer@1.0.6~start: CWD: C:\Program Files\nodejs\node_modules\micro-app-phone-dialer
10 silly lifecycle micro-app-phone-dialer@1.0.6~start: Args: [ '/d /s /c', 'node lib/server.js' ]
11 silly lifecycle micro-app-phone-dialer@1.0.6~start: Returned: code: 1  signal: null
12 info lifecycle micro-app-phone-dialer@1.0.6~start: Failed to exec start script
13 verbose stack Error: micro-app-phone-dialer@1.0.6 start: `node lib/server.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:305:20)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:305:20)
13 verbose stack     at maybeClose (internal/child_process.js:1028:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid micro-app-phone-dialer@1.0.6
15 verbose cwd C:\Program Files\nodejs\node_modules\micro-app-phone-dialer
16 verbose Windows_NT 10.0.14393
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v13.5.0
19 verbose npm  v6.13.4
20 error code ELIFECYCLE
21 error errno 1
22 error micro-app-phone-dialer@1.0.6 start: `node lib/server.js`
22 error Exit status 1
23 error Failed at the micro-app-phone-dialer@1.0.6 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

401 should be "Unauthorized" but i made an *.php site that is linked in the SEP file and is accessable.
`<authenticationURL>http://192.168.2.2/ciscoauth.php</authenticationURL>`
It´s an simple version:
```
<?php
echo "AUTHORIZED";
?>
```

But it´s works to make an screenshot with /CGI/Screenshot.

kind regards
Michael

**Comment by derandre24** [comment]
Hi Miachael,

the same goes for me. I also get a 401.

npm start   (node:23977) [DEP0022] DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.

> micro-app-phone-dialer@1.0.6 start /usr/local/lib/node_modules/micro-app-phone-dialer
> node lib/server.js


**/usr/local/lib/node_modules/micro-app-phone-dialer/lib/server.js:92
            throw(response.statusCode);
            ^
401**

npm ERR! micro-app-phone-dialer@1.0.6 start: `node lib/server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the micro-app-phone-dialer@1.0.6 start script.
npm ERR! This is most likely a problem with the micro-app-phone-dialer package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node lib/server.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls micro-app-phone-dialer
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 4.14.79+
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! cwd /usr/local/lib/node_modules/micro-app-phone-dialer
npm ERR! node -v v8.11.1
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /usr/local/lib/node_modules/micro-app-phone-dialer/npm-debug.log
npm ERR! not ok code 0


Regards
André

**Comment by mhdawson** [comment]
401 means "unauthorized". Assuming the phone IP and port are correct then my guess is that the API needs to be enabled in the phone.

**Comment by bredmich** [comment]
The API is working.
I already tried this simple *.php site from [chan-sccp](https://github.com/chan-sccp/chan-sccp/wiki/Push-CiscoIPPhoneExecute-Commands-to-Phone)
```
<?php
  // the cisco phone has ip address 192.168.0.129
  // and we are gone tell that phone to dial extension 301.
  // since the priority is 0, it will dial this number even if
  // there is a call in progress..

  $number2dial="301";
  $data='<CiscoIPPhoneExecute><ExecuteItem Priority="0" URL="Dial:'.$number2dial.'"/></CiscoIPPhoneExecute>';
  $ipv4="192.168.2.18";

  $response=cisco_voip_phone_xml_push($ipv4,$data);
  return;

  // push xml-like packet to cisco voip phone...
  function cisco_voip_phone_xml_push($ipv4,$data,$uid="web",$pwd="bot")
  {
     $auth=base64_encode($uid.":".$pwd);
     $xml="XML=".urlencode($data);

     $post="POST /CGI/Execute HTTP/1.0\r\n";
     $post.="Host: $ipv4\r\n";
     $post.="Authorization: Basic $auth\r\n";
     $post.="Connection: close\r\n";
     $post.="Content-Type: application/x-www-form-urlencoded\r\n";
     $post.="Content-Length: ".strlen($xml)."\r\n\r\n";

     $response="";
     $fp=fsockopen($ipv4,80,$errno,$errstr,30);
     if(!$fp) return false;

     fputs($fp,$post.$xml);
     while(!feof($fp))
     {
        $response=fgets($fp,128);
     }
     fclose($fp);
     return $response;
  }
?>
```

**Comment by mhdawson** [comment]
The next step would be to see if you can talk to the phone with https://www.npmjs.com/package/node-cti at that is what is used under the covers.

**Comment by bredmich** [comment]
I´ve to admit that i don´t understand how to use your Node-CTI :-(

**Comment by mhdawson** [comment]
What happens if you remove 
     $post.="Authorization: Basic $auth\r\n";

from your php example?

I don't think node-cti adds an Authorization header.

If you extracted the auth token and then changed lines 16 though 19 in node-modules/node-cit/lib/SendPhoneRequest.js to be:

  headers: { 
    'Content-Type': 'text/xml',
    'Content-Length': 0,
    'Authorization: Basic XXXX'
  }

were XXXX is the encoded auth token, that might fix the issue if your phone requires authorization.



where XXXX

**Comment by bredmich** [comment]
Ah that´s it!
After removing `$post.="Authorization: Basic $auth\r\n";` it´s not working anymore.
~~So could you guide me a little bit to at this to your Node-CTI?~~

Nevermind i got it!
And it´s working.
```
  headers: { 
    'Content-Type': 'text/xml',
    'Content-Length': 0,
	'Authorization': 'Basic d2ViOmJvdA=='
```

Thanks for your support Michael!
Andre and i are gonna like your work :-)

**Comment by mhdawson** [comment]
A  first step would be to hard code it into node-modules/node-cit/lib/SendPhoneRequest.js as shown above. If that works then I can think more about how an authorization option might be added.

**Comment by bredmich** [comment]
What i´m still wondering is why does it work with the base64_encode of uid=web and pwd=bot.
I´m using completely different values for my sshUserId and sshPassword in my SEP file.

Anyway, it´s working with the hardcoded value of the base64 encoded value of 'web:bot' like in my PHP example.

**Comment by mhdawson** [comment]
Thanks for confirming. For now if you can just hard code and then I'll try to look at an update this weekend.

**Comment by mhdawson** [comment]
Ok published new versions of node-cti and micro-app-phone-dialer which support adding
```
"basicAuth": "XXXX"
```
to the config file where XXXX is the encode auth token.

@bredmich can you check it out and confirm it works for you?

**Comment by bredmich** [comment]
Hi Michael
i updated node-cti and micro-app-phone-dialer and added the line `"bascicAuth": "d2ViOmJvdA==",` to my config.json between phoneIP and dialOptions.
The phone-dialer throws Error:401 when trying to dial something.
I already tried to modify it to be `"bascicAuth": "Basic d2ViOmJvdA==",` with the same result.

**Comment by derandre24** [comment]
Hi Michael,

for me it works fine. I can dial numbers. Only "Mute" and "Hang up" doesn't work. But that's not a problem for me. Dialing is important and that works. Thank you for your work.

**Comment by bredmich** [comment]
Ok my bad, i killed my nodejs installation.

It´s now working like expected.
